# frozen_string_literal: true

require 'cuprum/cli/files'

module Cuprum::Cli::Files
  # Command for generating templated files.
  class Generator
    extend  Cuprum::Cli::Options::ClassMethods
    include Cuprum::Cli::Options::Quiet
    include Cuprum::Cli::Options::Verbose

    # Raised when performing a protected operation on an abstract Generator.
    class AbstractGeneratorError < StandardError; end

    class << self
      # Marks the generator as abstract.
      def abstract = @abstract = true

      # @return [true, false] true if the generator is abstract and should not
      #   be assigned matchers or outputs; otherwise false.
      def abstract? = @abstract.nil? ? false : @abstract

      # @overload match_file(pattern)
      #   Registers the pattern as a valid match for the generator.
      #
      #   The registered matches are checked when the generator checks whether a
      #   file path can be generated by the generator.
      #
      #   - If the given pattern is a regular expression, the generator will
      #     match the pattern against the file path.
      #   - If the pattern is a string, the generator will check if the file
      #     path ends with the pattern string.
      #
      #   @param pattern [Regexp, String] the pattern to register.
      #
      #   @return [void]
      #
      # @overload match_file(&block)
      #   Registers the block as a valid match for the generator.
      #
      #   The registered matches are checked when the generator checks whether a
      #   file path can be generated by the generator. The given block will be
      #   called with the file path and generator options; if the block returns
      #   a truthy value, the match check returns true.
      #
      #   @yieldparam file_path [String] the input file path provided by the
      #     user.
      #   @yieldparam options [Hash] additional options for the generator.
      #
      #   @return [void]
      def match_file(pattern = nil, &block)
        if abstract?
          raise AbstractGeneratorError,
            abstract_generator_message('define matcher')
        end

        own_matchers << (block_given? ? block : pattern)

        nil
      end

      # @overload matches?(file_path, **options)
      #   Checks if the generator matches the given file path and options.
      #
      #   @param file_path [String] the input file path provided by the user.
      #   @param options [Hash] additional options for the generator.
      #
      #   @return [true, false] true if the generator can generate files with
      #   the given file type, path, and options; otherwise false.
      def matches?(file_path, **)
        matchers.any? do |matcher|
          case matcher
          when Proc   then matcher.call(file_path, **)
          when Regexp then matcher.match?(file_path)
          when String then file_path.end_with?(matcher)
          else
            # :nocov:
            false
            # :nocov:
          end
        end
      end
      alias match? matches?

      protected

      def matchers
        return [] if abstract?

        superclass.matchers.concat(own_matchers)
      end

      def own_matchers = @own_matchers ||= []

      private

      def abstract_generator_message(short_message)
        class_name =
          ancestors
          .find { |ancestor| ancestor.is_a?(Class) && ancestor.name }
          .name

        "unable to #{short_message} - #{class_name} is an abstract class"
      end
    end

    abstract

    option :dry_run, type: :boolean

    # @overload initialize(file_path, **options)
    #   @param file_path [String] the input file path provided by the user.
    #   @param options [Hash] additional options for the generator.
    #
    #   @option options dry_run [true, false] if true, simulates file generation
    #     but does not perform the actual file system operations. Defaults to
    #     false.
    #   @option options quiet [true, false] if true, does not print generated
    #     file names status to STDOUT. Defaults to false.
    #   @option options verbose [true, false] if true, prints the contents of
    #     generated files to STDOUT. Defaults to false.
    def initialize(file_path, **)
      @file_path = file_path
      @options   = self.class.resolve_options(**)
    end

    # @return [String] the input file path provided by the user.
    attr_reader :file_path

    # @return [Hash] additional options for the generator.
    attr_reader :options

    # @return [Hash] parameters extracted from the input file name.
    def file_parameters
      @file_parameters ||= extract_file_parameters(file_path)
    end

    private

    def extract_file_parameters(file_path) # rubocop:disable Metrics/MethodLength
      base_name = File.basename(file_path)
      segments  = file_path.split(File::SEPARATOR)

      {
        base_name:,
        dir_name:      File.dirname(file_path),
        ext_name:      File.extname(file_path),
        file_path:,
        relative_path: segments[1...-1].join(File::SEPARATOR),
        root_path:     segments[0...-1].first || '',
        short_name:    base_name.split('.').first
      }
    end

    def resolve_output_path(output_path)
      params = file_parameters.merge(options)

      format(output_path, params).gsub(%r{//+}, '/')
    end
  end
end
