# frozen_string_literal: true

require 'cuprum'
require 'plumbum'

require 'cuprum/cli/files'

module Cuprum::Cli::Files
  # Command for generating templated files.
  class Generator < Cuprum::Command # rubocop:disable Metrics/ClassLength
    include Plumbum::Consumer
    prepend Plumbum::Parameters
    extend  Cuprum::Cli::Options::ClassMethods
    include Cuprum::Cli::Options::Quiet
    include Cuprum::Cli::Options::Verbose

    # Raised when performing a protected operation on an abstract Generator.
    class AbstractGeneratorError < StandardError; end

    # Raised when performing a protected operation on an abstract Generator.
    class OutputAlreadyExistsError < KeyError; end

    # Data class representing a configured output file.
    Output = Data.define(:key, :path, :template_path)

    class << self
      # Marks the generator as abstract.
      def abstract = @abstract = true

      # @return [true, false] true if the generator is abstract and should not
      #   be assigned matchers or outputs; otherwise false.
      def abstract? = @abstract.nil? ? false : @abstract

      # @overload match_file(pattern)
      #   Registers the pattern as a valid match for the generator.
      #
      #   The registered matches are checked when the generator checks whether a
      #   file path can be generated by the generator.
      #
      #   - If the given pattern is a regular expression, the generator will
      #     match the pattern against the file path.
      #   - If the pattern is a string, the generator will check if the file
      #     path ends with the pattern string.
      #
      #   @param pattern [Regexp, String] the pattern to register.
      #
      #   @return [void]
      #
      # @overload match_file(&block)
      #   Registers the block as a valid match for the generator.
      #
      #   The registered matches are checked when the generator checks whether a
      #   file path can be generated by the generator. The given block will be
      #   called with the file path and generator options; if the block returns
      #   a truthy value, the match check returns true.
      #
      #   @yieldparam file_path [String] the input file path provided by the
      #     user.
      #   @yieldparam options [Hash] additional options for the generator.
      #
      #   @return [void]
      def match_file(pattern = nil, &block)
        if abstract?
          raise AbstractGeneratorError,
            abstract_generator_message('define matcher')
        end

        own_matchers << (block_given? ? block : pattern)

        nil
      end

      # @overload matches?(file_path, **options)
      #   Checks if the generator matches the given file path and options.
      #
      #   @param file_path [String] the input file path provided by the user.
      #   @param options [Hash] additional options for the generator.
      #
      #   @return [true, false] true if the generator can generate files with
      #   the given file type, path, and options; otherwise false.
      def matches?(file_path, **)
        matchers.any? do |matcher|
          case matcher
          when Proc   then matcher.call(file_path, **)
          when Regexp then matcher.match?(file_path)
          when String then file_path.end_with?(matcher)
          else
            # :nocov:
            false
            # :nocov:
          end
        end
      end
      alias match? matches?

      # Registers an output file for the generator.
      #
      # The output path parameter is a String that can include format strings,
      # which will be resolved from the options passed to the generator. In
      # addition, the format strings can reference the following parameters
      # derived from the input file_path. The following examples use an input
      # file path of "lib/path/to/file.rb":
      #
      # - base_name: The last segment of the file path, including the file
      #   extension. Example: "file.rb".
      # - dir_name: The directory path from the file path, relative to the
      #   working directory. Example: "lib/path/to".
      # - ext_name: The extension of the file path, including the leading
      #   period character. Example: ".rb".
      # - file_path: The full file path. Example: "lib/path/to/file.rb".
      # - relative_path: The *second and later* segments of the directory path,
      #   or an empty String if the path is too short. Example: "path/to".
      # - root_path: The *first* segment of the directory path, or an empty
      #   String if the path is too short. Example: "lib".
      # - short_name: The last segment of the file path, excluding the file
      #   extension. Example: "file".
      #
      # @param path [String] the file path for the generated file.
      # @param key [String, Symbol] a unique key used to identify the output.
      #   Defaults to :default.
      # @param template_path [String] the path to the template file for the
      #   output. If not provided, the user must provide a template for that output.
      #
      # @return [void]
      def output(path, key: :default, template_path: nil)
        key = key.to_sym

        if abstract?
          raise AbstractGeneratorError,
            abstract_generator_message("define output #{key.inspect}")
        end

        if own_outputs.key?(key)
          raise OutputAlreadyExistsError, output_already_exists_message(key)
        end

        own_outputs[key] = Output.new(key:, path:, template_path:)

        nil
      end

      # @return [Hash{Symbol => Output}] the configured outputs for the
      #   generator.
      def outputs
        return {} if abstract?

        superclass.outputs.merge(own_outputs)
      end

      protected

      def matchers
        return [] if abstract?

        superclass.matchers.concat(own_matchers)
      end

      def own_matchers = @own_matchers ||= []

      def own_outputs = @own_outputs ||= {}

      private

      def abstract_generator_message(short_message)
        class_name =
          ancestors
          .find { |ancestor| ancestor.is_a?(Class) && ancestor.name }
          .name

        "unable to #{short_message} - #{class_name} is an abstract class"
      end

      def output_already_exists_message(key)
        class_name =
          ancestors
          .find { |ancestor| ancestor.is_a?(Class) && ancestor.name }
          .name

        "unable to define output #{key.inspect} - #{class_name} already " \
          "defines output #{key.inspect}"
      end
    end

    abstract

    provider Cuprum::Cli::Dependencies.provider

    dependency :file_system
    dependency :standard_io

    option :dry_run, type: :boolean

    # @overload initialize(file_path, **options)
    #   @param file_path [String] the input file path provided by the user.
    #   @param options [Hash] additional options for the generator.
    #
    #   @option options dry_run [true, false] if true, simulates file generation
    #     but does not perform the actual file system operations. Defaults to
    #     false.
    #   @option options quiet [true, false] if true, does not print generated
    #     file names status to STDOUT. Defaults to false.
    #   @option options verbose [true, false] if true, prints the contents of
    #     generated files to STDOUT. Defaults to false.
    def initialize(file_path, **)
      super()

      @file_path = file_path
      @options   = self.class.resolve_options(**)
    end

    # @return [String] the input file path provided by the user.
    attr_reader :file_path

    # @return [Hash] additional options for the generator.
    attr_reader :options

    # @return [Hash] parameters extracted from the input file name.
    def file_parameters
      @file_parameters ||= extract_file_parameters(file_path)
    end

    private

    def extract_file_parameters(file_path) # rubocop:disable Metrics/MethodLength
      base_name = File.basename(file_path)
      segments  = file_path.split(File::SEPARATOR)

      {
        base_name:,
        dir_name:      File.dirname(file_path),
        ext_name:      File.extname(file_path),
        file_path:,
        relative_path: segments[1...-1].join(File::SEPARATOR),
        root_path:     segments[0...-1].first || '',
        short_name:    base_name.split('.').first
      }
    end

    def filter_outputs # rubocop:disable Metrics/MethodLength
      outputs = self.class.outputs

      if outputs.empty?
        error = generator_error(
          details: 'generator does not define any outputs'
        )
        return failure(error)
      end

      outputs = outputs.reject { |key, _| options[key] == false }

      return outputs unless outputs.empty?

      error = generator_error(details: 'all outputs have been disabled')
      failure(error)
    end

    def generate_command
      @generate_command ||=
        Cuprum::Cli::Commands::File::GenerateFile
        .new(
          dry_run:     dry_run?,
          file_system:,
          quiet:       quiet?,
          standard_io:,
          verbose:     verbose?
        )
    end

    def generate_file(file_path:, template_path:)
      parameters = file_parameters.merge(options)

      generate_command.call(file_path:, parameters:, template_path:)
    end

    def generator_error(details: nil, key: nil)
      message = 'unable to generate output file'
      message = "#{message}#{key ? " #{key.inspect}" : 's'}"
      message = "#{message} - #{details}" if details

      Cuprum::Cli::Errors::Files::GeneratorError.new(
        details:,
        file_path:,
        message:,
        options:
      )
    end

    def process
      outputs = step { filter_outputs }

      outputs.each_value do |output|
        file_path     = step { resolve_output_path(output) }
        template_path = step { template_path_for(output) }

        step { generate_file(file_path:, template_path:) }
      end
    end

    def resolve_output_path(output) # rubocop:disable Metrics/MethodLength
      params = file_parameters.merge(options).compact

      format(output.path, params).gsub(%r{//+}, '/')
    rescue KeyError => exception
      details =
        "missing parameter #{exception.key.inspect} for output path " \
        "#{output.path}"
      error = generator_error(
        details:,
        key:     output.key
      )
      failure(error)
    end

    def template_path_for(output) # rubocop:disable Metrics/MethodLength
      template_path =
        if output.key == :default && options[:template]
          options[:template]
        else
          options[:"#{output.key}_template"] || output.template_path
        end

      return template_path unless template_path.nil? || template_path.empty?

      error = generator_error(
        details: 'output does not define a template path',
        key:     output.key
      )
      failure(error)
    end
  end
end
